version: '3.8'

services:
    redis:
        image: redis
        ports:
          - 6379:6379            
    api:                
        image: python        
        ports:
          - 5000:5000
        depends_on:
          - redis  